'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("miniMates.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;credit&quot;: &quot;Made with Blockbench&quot;,
        '''	&quot;texture_size&quot;: [32, 32],
        '''	&quot;textures&quot;: {
        '''		&quot;0&quot;: &quot;texturePath&quot;,
        '''		&quot;particle&quot;: &quot;texturePath&quot;
        '''	},
        '''	&quot;elements&quot;: [
        '''		{
        '''			&quot;name&quot;: &quot;bodyInner&quot;,
        '''			&quot;from&quot;: [6, 0, 7],
        '''			&quot;to&quot;: [9, 4, 10],
        '''			&quot;faces&quot;: {
        '''				&quot;north&quot;: {&quot;uv&quot;: [5, 5, 7, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;east&quot;: {&quot;uv&quot;: [4, 5, 5, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;south&quot;: {&quot;uv&quot;: [8, 5, 10, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;west&quot;: {&quot;uv&quot;: [7, 5, 8, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;up&quot;: {&quot;uv&quot;: [7, 5, 5, 4], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;down&quot;: {&quot;uv&quot;: [9,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property baseMini() As String
            Get
                Return ResourceManager.GetString("baseMini", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;credit&quot;: &quot;Made with Blockbench&quot;,
        '''	&quot;texture_size&quot;: [32, 32],
        '''	&quot;textures&quot;: {
        '''		&quot;0&quot;: &quot;texture&quot;,
        '''		&quot;particle&quot;: &quot;texture&quot;
        '''	},
        '''	&quot;elements&quot;: [
        '''		{
        '''			&quot;name&quot;: &quot;body&quot;,
        '''			&quot;from&quot;: [6, 0, 7],
        '''			&quot;to&quot;: [9, 4, 10],
        '''			&quot;faces&quot;: {
        '''				&quot;north&quot;: {&quot;uv&quot;: [5, 10, 7, 16.5], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;east&quot;: {&quot;uv&quot;: [4, 10, 5, 16.5], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;south&quot;: {&quot;uv&quot;: [8, 10, 10, 16.5], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;west&quot;: {&quot;uv&quot;: [7, 10, 8, 16.5], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;up&quot;: {&quot;uv&quot;: [7, 10, 5, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;down&quot;: {&quot;uv&quot;:  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property baseMini_oldSkin() As String
            Get
                Return ResourceManager.GetString("baseMini_oldSkin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''	&quot;credit&quot;: &quot;Made with Blockbench&quot;,
        '''	&quot;texture_size&quot;: [32, 32],
        '''	&quot;textures&quot;: {
        '''		&quot;0&quot;: &quot;texture&quot;,
        '''		&quot;particle&quot;: &quot;texture&quot;
        '''	},
        '''	&quot;elements&quot;: [
        '''		{
        '''			&quot;name&quot;: &quot;bodyInner&quot;,
        '''			&quot;from&quot;: [6, 0, 7],
        '''			&quot;to&quot;: [9, 4, 10],
        '''			&quot;faces&quot;: {
        '''				&quot;north&quot;: {&quot;uv&quot;: [5, 5, 7, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;east&quot;: {&quot;uv&quot;: [4, 5, 5, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;south&quot;: {&quot;uv&quot;: [8, 5, 10, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;west&quot;: {&quot;uv&quot;: [7, 5, 8, 8], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;up&quot;: {&quot;uv&quot;: [7, 5, 5, 4], &quot;texture&quot;: &quot;#0&quot;},
        '''				&quot;down&quot;: {&quot;uv&quot;: [9, 4, 7, 5] [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property baseMini_slim() As String
            Get
                Return ResourceManager.GetString("baseMini_slim", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blacklayer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blacklayer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blacklayer_old() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blacklayer_old", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blacklayer_slim() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blacklayer_slim", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;sources&quot;: []}.
        '''</summary>
        Friend ReadOnly Property emptyblockjson() As String
            Get
                Return ResourceManager.GetString("emptyblockjson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;overrides&quot;: [], &quot;parent&quot;: &quot;item/generated&quot;, &quot;textures&quot;: {&quot;layer0&quot;: &quot;item/paper&quot;}}.
        '''</summary>
        Friend ReadOnly Property emptyItemJson() As String
            Get
                Return ResourceManager.GetString("emptyItemJson", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {&quot;pack&quot;: {&quot;description&quot;: &quot;\u00a77\u00a7oMiniMates\n\u00a77v1.0 \u00a78\u2022 \u00a771.20.x \u00a78\u2022 \u00a7cby ProfessorStrange&quot;, &quot;pack_format&quot;: 22}}.
        '''</summary>
        Friend ReadOnly Property emptyPackmcdata() As String
            Get
                Return ResourceManager.GetString("emptyPackmcdata", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
